function [ data ] = import_data( ...
    nb_input, nb_output, fifo_depth, arbiter_mode, ...
    exec_time, stream_period)

data = csvread( ...
    strcat('../data/noc_', int2str(nb_input), '_', ...
    int2str(nb_output), '_', int2str(fifo_depth), '_', ...
    int2str(arbiter_mode), '_', int2str(exec_time), '_', ...
    int2str(stream_period), '_packet_trace.data'));

data(:,4) = data(:,3) - data(:,2);
data(:,5) = data(:,3) - data(:,2);

end

